name: Install Python and Run Script-vinayashree

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # You can change this to any version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python version
        run: python --version
      - name: Run Python print statement
        run: |
          python -c "print('Hello from GitHub Actions!')"
      - name: Run Python script file
        run: |
          pwd
          ls -lrt
          python script.py
      - name: Run pytest
        run: pytest
